# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "pt-BR"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  auto_title_placeholder: "@coderabbitai"
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  auto_review:
    enabled: true
    drafts: true
chat:
  auto_reply: true